### ISSUE TITLE
Want to add 90, 180 & 270 degree rotation of images

### ISSUE THREAD

**Issue by nauman-khattak** [nauman-khattak/DIP_Project#1]
I want to add rotation functionality of images to my project.
The user can select from Jmenu whether to rotate 90, 180 or 270 degrees. The image should be rotated then. Any contribution would be appreciated. Thanks

**Comment by nauman-khattak** [comment]
Should i create a separate `JMenu` for rotation or you want to add `JMenuItem` to existing menu?

**Comment by quadeinc** [comment]
Should i create a separate JMenu for rotation or you want to add JMenuItem to existing menu?

**Comment by quadeinc** [comment]
I cloned your project. I'm working on adding photo rotation functionality to your project. 
I just want to know that shall i create a separate `JMenu` for rotation or you want to add `JMenuItem` to existing menu?

**Comment by nauman-khattak** [comment]
You can create a JMenu lets say **Rotate** which will contain 3 JMenuItems 
1. Rotate 90 degrees
2. Rotate 180 degrees
3. Rotate 270 degrees

When the user clicks on one of the above three rotation choices then image should rotate accordingly. I can add this GUI portion myself and you can add actual functionality.

**Comment by quadeinc** [comment]
I added code for rotation. I created pull request. Check it out

**Comment by nauman-khattak** [comment]
@quadeinc I checked the code and thats exactly what i want.  You made my day thankyou so much.
